//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_commercestore
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        public int Id { get; set; }
        public System.DateTime generationtime { get; set; }
        public bool ispaid { get; set; }
        public int amount { get; set; }
        public string paymentmethod { get; set; }
        public int orderId { get; set; }
    
        public virtual order order { get; set; }
    }
}
