//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_commercestore
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderproduct
    {
        public int Id { get; set; }
        public int quantity { get; set; }
        public int orderId { get; set; }
        public int productId { get; set; }
    
        public virtual order order { get; set; }
        public virtual product product { get; set; }
    }
}
